services:
  server:
    image: xlj420/printer:latest
    container_name: printer-server
    restart: unless-stopped
    ports:
      - '8001:3000'
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - printer_uploads:/app/uploads

volumes:
  printer_uploads:
